### ISSUE TITLE
Hey there!!

### ISSUE THREAD

**Issue by CT-40** [datromax/datromax#1]
I don’t mean to offend, but is this a serious project or a “Just for fun” project? 
If serious, will there be a discord or telegram for a community?

Thanks for your time.

**Comment by x23101983** [comment]
Official Links
Website: https://datromax.com/
Explorer: https://explorer.datromax.com/
Twitter: https://x.com/datromax
Telegram: https://t.me/datromax
Github: https://github.com/datromax
Bitcointalk: https://bitcointalk.org/index.php?topic=5512995
Node: https://explorer.datromax.com/network
Discord: https://discord.gg/3y2j7T3y
